/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_alpro2;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

/**
 *
 * @author Indrajaya-PC
 */
public class soal2 extends javax.swing.JFrame {

        String[] questions = {"1.Huruf manakah mana yang berbunyi (a-ba-a) ","2.Huruf manakah mana yang berbunyi (tsa-a-da) ","3.Huruf manakah mana yang berbunyi (ra-ma-wa) ","4.Huruf manakah mana yang berbunyi (la-ka-fa) ","5.Huruf manakah mana yang berbunyi (na-a-ma) ",};
        String[][] options = {{"اَ ثَ اَ","اَ بَ اَ","اَ بَ اَ"},{"ثَ اَ دَ","تَ اَ ذَ","ثَ اَ دَ"},{"رَ وَ قَ","رَ مَ وَ","رَ مَ وَ"},{"لَ كَ فَ","لَ رَ زَ","لَ كَ فَ"},{"نَ ذَ اَ","نَ اَ مَ","نَ اَ مَ"}};
    
//        String[] questions = {"1.Huruf manakah mana yang berbunyi (a-ba-a) ","2.Huruf manakah mana yang berbunyi (tsa-a-da) ","3.Huruf manakah mana yang berbunyi (ra-za-sa) ","4.Huruf manakah mana yang berbunyi (na-fa-ka) ","5.Huruf manakah mana yang berbunyi (wa-ma-ya) "};
//        String[][] options = {{"اَ ثَ اَ","اَ بَ اَ","اَ بَ اََ"},{"ثَ اَ دَ","تَ اَ ذَ","ثَ اَ دَ"},{"رَ زَ سَ","زَ رَ شَ","رَ زَ سَ"},{"بَ فَ قَ","نَ فَ كَ","نَ فَ كَ"},{"وَ مَ اَ","وَ مَ ىَ","وَ مَ ىَ"}};
        int index = 0, correct = 0;
        ButtonGroup bg = new ButtonGroup();
    /**
     * Creates new form hurufhijaiyah
     */
    public soal2() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bg.add(jRadioButton1_);
        bg.add(jRadioButton2_);
        
        jButton_Next_QActionPerformed(null);
    }
    
    public void getSelectedOption(JRadioButton rbtn)
    {     
    if(rbtn.getText().equals(options[index][2]))
    {
        correct++;
    }           
        index++;
        enableRbuttons(false);
    }
    
    public void enableRbuttons(boolean yes_or_no)
    {
       jRadioButton1_.setEnabled(yes_or_no);
       jRadioButton2_.setEnabled(yes_or_no);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        panel4 = new javax.swing.JPanel();
        jPanel_Q_Container = new javax.swing.JPanel();
        Lbl_Question = new javax.swing.JLabel();
        jButton_Next_Q = new javax.swing.JButton();
        jRadioButton1_ = new javax.swing.JRadioButton();
        jRadioButton2_ = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Belajar Huruf Hijaiyyah");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panelutama.setPreferredSize(new java.awt.Dimension(1920, 1080));
        panelutama.setLayout(new java.awt.CardLayout());

        panel4.setLayout(null);

        jPanel_Q_Container.setBackground(new java.awt.Color(255, 204, 0));

        Lbl_Question.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Lbl_Question.setText("Soal");

        javax.swing.GroupLayout jPanel_Q_ContainerLayout = new javax.swing.GroupLayout(jPanel_Q_Container);
        jPanel_Q_Container.setLayout(jPanel_Q_ContainerLayout);
        jPanel_Q_ContainerLayout.setHorizontalGroup(
            jPanel_Q_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Q_ContainerLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(Lbl_Question)
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel_Q_ContainerLayout.setVerticalGroup(
            jPanel_Q_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Q_ContainerLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(Lbl_Question)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        panel4.add(jPanel_Q_Container);
        jPanel_Q_Container.setBounds(540, 240, 830, 295);

        jButton_Next_Q.setBackground(new java.awt.Color(255, 204, 0));
        jButton_Next_Q.setFont(new java.awt.Font("Sitka Text", 1, 22)); // NOI18N
        jButton_Next_Q.setText("Selanjutnya");
        jButton_Next_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Next_QActionPerformed(evt);
            }
        });
        panel4.add(jButton_Next_Q);
        jButton_Next_Q.setBounds(870, 750, 187, 50);

        jRadioButton1_.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        jRadioButton1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_ActionPerformed(evt);
            }
        });
        panel4.add(jRadioButton1_);
        jRadioButton1_.setBounds(680, 590, 230, 130);

        jRadioButton2_.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        jRadioButton2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_ActionPerformed(evt);
            }
        });
        panel4.add(jRadioButton2_);
        jRadioButton2_.setBounds(1080, 590, 230, 130);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/jlabel button/4.png"))); // NOI18N
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        panel4.add(jLabel31);
        jLabel31.setBounds(260, 65, 100, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kuis baca fix.png"))); // NOI18N
        panel4.add(jLabel5);
        jLabel5.setBounds(0, 0, 1920, 1080);

        panelutama.add(panel4, "panel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1892, 913));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Next_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Next_QActionPerformed
        // TODO add your handling code here:
        if(jButton_Next_Q.getText() .equals("Ulangi"))
        {
            jButton_Next_Q.setText("Selanjutnya");
            jPanel_Q_Container.setBackground(Color.orange);
            index = 0;
            correct = 0;
        }

        if(index == questions.length)
        {
            Lbl_Question.setText("                            Skor: "+correct+"/"+questions.length);
//            Lbl_Question.setForeground(Color.white);
            if(correct >= (float) questions.length/2)
            {
                jPanel_Q_Container.setBackground(Color.green);
            }
            else{
                jPanel_Q_Container.setBackground(Color.red);
            }
            jButton_Next_Q.setText("Ulangi");

        }

        else{
            enableRbuttons(true);

            Lbl_Question.setText(questions[index]);
            jRadioButton1_.setText(options[index][0]);
            jRadioButton2_.setText(options[index][1]);

            jButton_Next_Q.setText("Selanjutnya");
        }

        bg.clearSelection();
    }//GEN-LAST:event_jButton_Next_QActionPerformed

    private void jRadioButton2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_ActionPerformed
        // TODO add your handling code here:
        getSelectedOption(jRadioButton2_);
    }//GEN-LAST:event_jRadioButton2_ActionPerformed

    private void jRadioButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_ActionPerformed
        // TODO add your handling code here:
        getSelectedOption(jRadioButton1_);
    }//GEN-LAST:event_jRadioButton1_ActionPerformed

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        CardLayout cLayout = (CardLayout) panelutama.getLayout();
        cLayout.show(panelutama, "panel10");    
        hurufhijaiyah hurufhijaiyah = new hurufhijaiyah();
            hurufhijaiyah.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jLabel31MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new soal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_Question;
    private javax.swing.JButton jButton_Next_Q;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel_Q_Container;
    private javax.swing.JRadioButton jRadioButton1_;
    private javax.swing.JRadioButton jRadioButton2_;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panelutama;
    // End of variables declaration//GEN-END:variables
}
